-- Run this only if the meals table or meals-images bucket is missing.
-- The columns match the data contract used by lib/meals.jsx.

create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  image text not null,
  summary text not null,
  instructions text not null,
  creator text not null,
  creator_email text not null
);

alter table public.meals enable row level security;

create policy "Anyone can read meals"
on public.meals for select
to anon, authenticated
using (true);

create policy "Anyone can submit meals"
on public.meals for insert
to anon, authenticated
with check (true);


create policy "Anyone can read meal images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'meals-images');

create policy "Anyone can upload meal images"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'meals-images');
